# Generated by Django 4.2.4 on 2023-10-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bounty_title", models.CharField(default="", max_length=150)),
                ("location", models.CharField(default="", max_length=150)),
                ("despriction", models.TextField()),
                ("overview", models.TextField()),
                ("responsibilities", models.TextField()),
                ("qualifications", models.TextField()),
                ("inclosing", models.TextField()),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bounty_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="", max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_title", models.CharField(default="", max_length=150)),
                ("intro", models.TextField()),
                ("overview", models.TextField()),
                ("why_support", models.TextField()),
                ("how_to_help", models.TextField()),
                ("qr_code", models.ImageField(upload_to="donate_qr/")),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bounties.bounty",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bounty",
            name="category_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bounties.bounty_category",
            ),
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apply_title", models.CharField(default="", max_length=150)),
                ("intro", models.TextField()),
                ("why_contribute", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="uploads/resumes/")),
                ("cover_letter", models.FileField(upload_to="uploads/cover_letters/")),
                (
                    "portfolio",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/portfolios/"
                    ),
                ),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bounties.bounty",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Applications",
            },
        ),
    ]
