# Generated by Django 4.2.4 on 2023-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="uploads/resumes/")),
                ("cover_letter", models.FileField(upload_to="uploads/cover_letters/")),
                (
                    "portfolio",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/portfolios/"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="apply",
            name="cover_letter",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="email",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="name",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="portfolio",
        ),
        migrations.RemoveField(
            model_name="apply",
            name="resume",
        ),
    ]
